OGLR2D_OPENGL_FUNC(void, PFNGLBINDVERTEXARRAYPROC, glBindVertexArray, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays, (GLsizei, const GLuint*));
OGLR2D_OPENGL_FUNC(void, PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays, (GLsizei, GLuint*));
OGLR2D_OPENGL_FUNC(void, PFNGLGENBUFFERSPROC, glGenBuffers, (GLsizei, GLuint*));
OGLR2D_OPENGL_FUNC(void, PFNGLBINDBUFFERPROC, glBindBuffer, (GLenum, GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLDELETEBUFFERSPROC, glDeleteBuffers, (GLsizei, const GLuint*));
OGLR2D_OPENGL_FUNC(void, PFNGLBUFFERDATAPROC, glBufferData, (GLenum, GLsizeiptr, const void*, GLenum));
OGLR2D_OPENGL_FUNC(void, PFNGLBUFFERSUBDATAPROC, glBufferSubData, (GLenum, GLintptr, GLsizeiptr, const void*));
OGLR2D_OPENGL_FUNC(void, PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void*));
OGLR2D_OPENGL_FUNC(GLuint, PFNGLCREATEPROGRAMPROC, glCreateProgram, (void));
OGLR2D_OPENGL_FUNC(GLuint, PFNGLCREATESHADERPROC, glCreateShader, (GLenum));
OGLR2D_OPENGL_FUNC(void, PFNGLDELETEPROGRAMPROC, glDeleteProgram, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLDELETESHADERPROC, glDeleteShader, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLDETACHSHADERPROC, glDetachShader, (GLuint, GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLGETPROGRAMIVPROC, glGetProgramiv, (GLuint, GLenum, GLint*));
OGLR2D_OPENGL_FUNC(void, PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog, (GLuint, GLsizei, GLsizei*, GLchar*));
OGLR2D_OPENGL_FUNC(void, PFNGLGETSHADERIVPROC, glGetShaderiv, (GLuint, GLenum, GLint*));
OGLR2D_OPENGL_FUNC(void, PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei*, GLchar*));
OGLR2D_OPENGL_FUNC(GLint, PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation, (GLuint, const GLchar*));
OGLR2D_OPENGL_FUNC(void, PFNGLLINKPROGRAMPROC, glLinkProgram, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLSHADERSOURCEPROC, glShaderSource, (GLuint, GLsizei, const GLchar* const*, const GLint*));
OGLR2D_OPENGL_FUNC(void, PFNGLUSEPROGRAMPROC, glUseProgram, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLVALIDATEPROGRAMPROC, glValidateProgram, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM1FPROC, glUniform1f, (GLint, GLfloat));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM2FPROC, glUniform2f, (GLint, GLfloat, GLfloat));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM3FPROC, glUniform3f, (GLint, GLfloat, GLfloat, GLfloat));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM4FPROC, glUniform4f, (GLint, GLfloat, GLfloat, GLfloat, GLfloat));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM1IPROC, glUniform1i, (GLint, GLint));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM2IPROC, glUniform2i, (GLint, GLint, GLint));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM3IPROC, glUniform3i, (GLint, GLint, GLint, GLint));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORM4IPROC, glUniform4i, (GLint, GLint, GLint, GLint, GLint));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORMMATRIX2FVPROC, glUniformMatrix2fv, (GLint, GLsizei, GLboolean, const GLfloat*));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORMMATRIX2FVPROC, glUniformMatrix3fv, (GLint, GLsizei, GLboolean, const GLfloat*));
OGLR2D_OPENGL_FUNC(void, PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat*));
OGLR2D_OPENGL_FUNC(void, PFNGLCOMPILESHADERPROC, glCompileShader, (GLuint));
OGLR2D_OPENGL_FUNC(void, PFNGLATTACHSHADERPROC, glAttachShader, (GLuint, GLuint));
